version: '3.8'

services:
  feed-postgres:
    image: postgres:latest
    container_name: feed-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: donghyeon
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: feed-service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U donghyeon -d feed-service"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - feed-service-postgres-data:/var/lib/postgresql/data
  
  feed-redis:
    image: redis:latest
    container_name: feed-redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
  
  locust-master:
    image: locustio/locust
    container_name: locust-master
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile-feedItem.py --master -H http://host.docker.internal:9010
    depends_on:
      - feed-postgres
      - feed-redis

  locust-worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile-feedItem.py --worker --master-host locust-master
    depends_on:
      - locust-master


volumes:
  feed-service-postgres-data:
  redis_data:
